### ISSUE TITLE
Jujutsu 0.24 release

### ISSUE THREAD

**Issue by clearfram3** [steveklabnik/jujutsu-tutorial#52]
First... Thanks for all the work you do—you really have an impact on so many people!

My understanding is that you intended to rework the whole tutorial pretty soon, so I wanted to bring the recent [JJ 0.24 release](https://github.com/martinvonz/jj/releases) to your attention. It seems to have more breaking changes than 0.23, 0.22, and 0.21 combined, so I hope you can continue developing the tutorial with these updates in mind.

**Comment by steveklabnik** [comment]
Thank you! I am excited about 0.24 for sure. absorb seems really, really cool.

I will be taking it into account, and in the meantime, if anyone spots things that end up being wrong in this version for that release, I will happily merge pull requests about it.

**Comment by clearfram3** [comment]
Would you please add the date and version that the tutorial was updated for to the the main page?

**Comment by steveklabnik** [comment]
The version is listed at https://steveklabnik.github.io/jujutsu-tutorial/hello-world/how-to-install.html; I am not likely to find the time to do any work updating anything in the next week or two

**Comment by digital-carver** [comment]
It would be helpful to have some clear info on versions and what is up to date. 

The "How to install" page you mention says it's written at version 0.23.0. The [official docs](https://jj-vcs.github.io/jj/v0.25.0/tutorial/) show the version as 0.25.0, but also say:
> This tutorial has become somewhat out of date. Many people find the alternative (not quite finished) [tutorial by Steve Klabnik](https://steveklabnik.github.io/jujutsu-tutorial/) helpful.

So is that tutorial outdated, or is it just that segment of the text that's outdated, and the official docs are the more up-to-date ones? Both repos seem to have pretty recent commits, so that's not a clear indicator either. 

Which of the tutorials is actually up to date, and how much does that matter? (One might assume 0.23 -> 0.25 would be minor changes that don't matter to a beginner, but it could also be the case that there's some conceptual differences that make things unnecessarily confusing if one starts at 0.23 - I don't know which is the case, and wouldn't want to blindly assume!)

**Comment by steveklabnik** [comment]
> So is that tutorial outdated,

Both are not necessarily up to date. I decided to write my tutorial, and there's talk of upstreaming it, so upstream hasn't been working on rehauling their tutorial, but then I haven't had time to finish off my own. I've accepted some PRs to update some things, but haven't holistically updated things yet.

> how much does that matter?

It just means that if something errors when it says it should work, it may not be you, it may be that the example is wrong. jj is still pre-1.0, and so things are subject to change. Big concepts aren't necessarily changing, but for example, when I originally wrote this, bookmarks were called branches.

if i had a way to CI this, it would be much easier to ensure it was up to date, but that's non-trivial.
